#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jan 15, 2019 01:19:21 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global tch57
    tch57 = StringVar()
    global tch58
    tch58 = StringVar()
    global tch59
    tch59 = StringVar()
    global tch60
    tch60 = StringVar()
    global tch61
    tch61 = StringVar()
    global tch62
    tch62 = StringVar()
    global tch63
    tch63 = StringVar()
    global tch64
    tch64 = StringVar()
    global tch65
    tch65 = StringVar()
    global tch66
    tch66 = StringVar()
    global tch67
    tch67 = StringVar()
    global tch68
    tch68 = StringVar()
    global tch69
    tch69 = StringVar()
    global tch70
    tch70 = StringVar()
    global tch71
    tch71 = StringVar()
    global tch72
    tch72 = StringVar()
    global tch73
    tch73 = StringVar()
    global tch74
    tch74 = StringVar()
    global tch75
    tch75 = StringVar()
    global tch76
    tch76 = StringVar()


cost=[99999,10,20,35,25,50,60,65,30,50,20,75,100,90,120,150,80,70,110,130,50]
def calculatePrice():
    #print(w.chocolates.state())
    #print(w.TEntry3.get())
    active=[]
    totalcost=0
    states=[w.chocolates.state(),w.icecreams.state(),w.TCheckbutton3.state(),w.TCheckbutton4.state(),w.TCheckbutton5.state(),w.cabbage.state(),w.brinjal.state(),w.carrot.state(),w.cauliflower.state(),w.lemon.state(),w.sweetcorn.state(),w.rice.state(),w.potato.state(),w.mangoes.state(),w.strawberry.state(),w.guava.state(),w.pomegranate.state(),w.gulabjamun.state(),w.rasagulla.state(),w.cooldrink.state()  ]

    quantity=[w.TEntry1.get(),w.TEntry2.get(),w.TEntry3.get(),w.TEntry4.get(),w.TEntry5.get(),w.TEntry6.get(),w.TEntry7.get(),w.TEntry8.get(),w.TEntry9.get(),w.TEntry10.get(),w.TEntry11.get(),w.TEntry12.get(),w.TEntry13.get(),w.TEntry14.get(),w.TEntry15.get(),w.TEntry16.get(),w.TEntry17.get(),w.TEntry18.get(),w.TEntry19.get(),w.TEntry20.get(),]

    
    for each in range(0,len(states)):
        active.append(states[each])
    
    #print(active)
    for each in range(0,len(active)):
        if len(active[each])!=0:
            totalcost=totalcost+(int(quantity[each])*cost[each+1])
            
            
    print(totalcost)
    

    


    

    #print('market_menu1_support.calculatePrice')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import market_menu1
    market_menu1.vp_start_gui()

