#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jan 15, 2019 01:19:07 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import market_menu1_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    market_menu1_support.set_Tk_var()
    top = MarketMenu (root)
    market_menu1_support.init(root, top)
    root.mainloop()

w = None
def create_MarketMenu(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    market_menu1_support.set_Tk_var()
    top = MarketMenu (w)
    market_menu1_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MarketMenu():
    global w
    w.destroy()
    w = None


class MarketMenu:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Century Gothic} -size 20 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family Constantia -size 28 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family Constantia -size 17 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1920x974+-409+3")
        top.title("MarketMenu")
        top.configure(background="#99d897")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Message1 = Message(top)
        self.Message1.place(relx=-0.01, rely=0.0, relheight=1.0, relwidth=0.29)
        self.Message1.configure(background="#d8d27b")
        self.Message1.configure(font=font10)
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Market Menu

1.Chocolates      - 10/-
2.IceCreams       - 20/-
3.Onions          - 35/-  
4.Tomatoes        - 25/-    
5.Lady's Finger   - 50/-  
6.Cabbage         - 60/-
7.Brinjal         - 65/-
8.Carrot          - 30/-
9.Cauliflower     - 50/-
10.Lemon          - 20/-
11.SweetCorn      - 75/-
12.Rice           - 100/-
13.Potato         - 90/-
14.Mangoes        - 120/-
15.Strawberry     - 150/-
16.Guava          - 80/-
17.Pomegranate    - 70/-
18.Gulab Jamun    - 110/-
19.Rasagulla      - 130/-
20.CoolDrink      - 50/-''')
        self.Message1.configure(width=565)

        self.TLabel1 = ttk.Label(top)
        self.TLabel1.place(relx=0.33, rely=0.03, height=39, width=384)
        self.TLabel1.configure(background="#86acd8")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font=font9)
        self.TLabel1.configure(relief=FLAT)
        self.TLabel1.configure(text='''Select Your Items and Quantity''')

        self.style.map('TCheckbutton',background=
            [('selected', _bgcolor), ('active', _ana2color)])
        self.chocolates = ttk.Checkbutton(top)
        self.chocolates.place(relx=0.34, rely=0.12, relwidth=0.09, relheight=0.0
                , height=23)
        self.chocolates.configure(variable=market_menu1_support.tch57)
        self.chocolates.configure(onvalue="0")
        self.chocolates.configure(takefocus="")
        self.chocolates.configure(text='''Chocolates''')

        self.icecreams = ttk.Checkbutton(top)
        self.icecreams.place(relx=0.34, rely=0.16, relwidth=0.09, relheight=0.0
                , height=23)
        self.icecreams.configure(variable=market_menu1_support.tch58)
        self.icecreams.configure(takefocus="")
        self.icecreams.configure(text='''IceCreams''')

        self.TCheckbutton3 = ttk.Checkbutton(top)
        self.TCheckbutton3.place(relx=0.34, rely=0.21, relwidth=0.08
                , relheight=0.0, height=23)
        self.TCheckbutton3.configure(variable=market_menu1_support.tch59)
        self.TCheckbutton3.configure(takefocus="")
        self.TCheckbutton3.configure(text='''Onions''')

        self.TCheckbutton4 = ttk.Checkbutton(top)
        self.TCheckbutton4.place(relx=0.34, rely=0.25, relwidth=0.08
                , relheight=0.0, height=23)
        self.TCheckbutton4.configure(variable=market_menu1_support.tch60)
        self.TCheckbutton4.configure(takefocus="")
        self.TCheckbutton4.configure(text='''Tomatoes''')

        self.TCheckbutton5 = ttk.Checkbutton(top)
        self.TCheckbutton5.place(relx=0.34, rely=0.29, relwidth=0.08
                , relheight=0.0, height=23)
        self.TCheckbutton5.configure(variable=market_menu1_support.tch61)
        self.TCheckbutton5.configure(takefocus="")
        self.TCheckbutton5.configure(text='''Lady's Finger''')

        self.cabbage = ttk.Checkbutton(top)
        self.cabbage.place(relx=0.35, rely=0.33, relwidth=0.08, relheight=0.0
                , height=23)
        self.cabbage.configure(variable=market_menu1_support.tch62)
        self.cabbage.configure(takefocus="")
        self.cabbage.configure(text='''Cabbage''')

        self.brinjal = ttk.Checkbutton(top)
        self.brinjal.place(relx=0.35, rely=0.37, relwidth=0.08, relheight=0.0
                , height=23)
        self.brinjal.configure(variable=market_menu1_support.tch63)
        self.brinjal.configure(takefocus="")
        self.brinjal.configure(text='''Brinjal''')

        self.carrot = ttk.Checkbutton(top)
        self.carrot.place(relx=0.35, rely=0.41, relwidth=0.08, relheight=0.0
                , height=23)
        self.carrot.configure(variable=market_menu1_support.tch64)
        self.carrot.configure(takefocus="")
        self.carrot.configure(text='''Carrot''')

        self.cauliflower = ttk.Checkbutton(top)
        self.cauliflower.place(relx=0.34, rely=0.45, relwidth=0.09, relheight=0.0
                , height=23)
        self.cauliflower.configure(variable=market_menu1_support.tch65)
        self.cauliflower.configure(takefocus="")
        self.cauliflower.configure(text='''Cauliflower''')

        self.lemon = ttk.Checkbutton(top)
        self.lemon.place(relx=0.35, rely=0.49, relwidth=0.08, relheight=0.0
                , height=23)
        self.lemon.configure(variable=market_menu1_support.tch66)
        self.lemon.configure(takefocus="")
        self.lemon.configure(text='''Lemon''')

        self.sweetcorn = ttk.Checkbutton(top)
        self.sweetcorn.place(relx=0.34, rely=0.53, relwidth=0.09, relheight=0.0
                , height=23)
        self.sweetcorn.configure(variable=market_menu1_support.tch67)
        self.sweetcorn.configure(takefocus="")
        self.sweetcorn.configure(text='''SweetCorn''')

        self.rice = ttk.Checkbutton(top)
        self.rice.place(relx=0.34, rely=0.57, relwidth=0.08, relheight=0.0
                , height=23)
        self.rice.configure(variable=market_menu1_support.tch68)
        self.rice.configure(takefocus="")
        self.rice.configure(text='''Rice''')

        self.potato = ttk.Checkbutton(top)
        self.potato.place(relx=0.34, rely=0.62, relwidth=0.09, relheight=0.0
                , height=23)
        self.potato.configure(variable=market_menu1_support.tch69)
        self.potato.configure(takefocus="")
        self.potato.configure(text='''Potato''')

        self.mangoes = ttk.Checkbutton(top)
        self.mangoes.place(relx=0.35, rely=0.66, relwidth=0.08, relheight=0.0
                , height=23)
        self.mangoes.configure(variable=market_menu1_support.tch70)
        self.mangoes.configure(takefocus="")
        self.mangoes.configure(text='''Mangoes''')

        self.strawberry = ttk.Checkbutton(top)
        self.strawberry.place(relx=0.35, rely=0.7, relwidth=0.08, relheight=0.0
                , height=23)
        self.strawberry.configure(variable=market_menu1_support.tch71)
        self.strawberry.configure(takefocus="")
        self.strawberry.configure(text='''Strawberry''')

        self.guava = ttk.Checkbutton(top)
        self.guava.place(relx=0.35, rely=0.74, relwidth=0.08, relheight=0.0
                , height=23)
        self.guava.configure(variable=market_menu1_support.tch72)
        self.guava.configure(takefocus="")
        self.guava.configure(text='''Guava''')

        self.pomegranate = ttk.Checkbutton(top)
        self.pomegranate.place(relx=0.34, rely=0.78, relwidth=0.09, relheight=0.0
                , height=23)
        self.pomegranate.configure(variable=market_menu1_support.tch73)
        self.pomegranate.configure(takefocus="")
        self.pomegranate.configure(text='''Pomegranate''')

        self.gulabjamun = ttk.Checkbutton(top)
        self.gulabjamun.place(relx=0.34, rely=0.82, relwidth=0.09, relheight=0.0
                , height=23)
        self.gulabjamun.configure(variable=market_menu1_support.tch74)
        self.gulabjamun.configure(takefocus="")
        self.gulabjamun.configure(text='''Gulab Jamun''')

        self.rasagulla = ttk.Checkbutton(top)
        self.rasagulla.place(relx=0.35, rely=0.86, relwidth=0.08, relheight=0.0
                , height=23)
        self.rasagulla.configure(variable=market_menu1_support.tch75)
        self.rasagulla.configure(takefocus="")
        self.rasagulla.configure(text='''Rasagulla''')

        self.cooldrink = ttk.Checkbutton(top)
        self.cooldrink.place(relx=0.35, rely=0.9, relwidth=0.08, relheight=0.0
                , height=23)
        self.cooldrink.configure(variable=market_menu1_support.tch76)
        self.cooldrink.configure(takefocus="")
        self.cooldrink.configure(text='''CoolDrink''')

        self.TEntry1 = ttk.Entry(top)
        self.TEntry1.place(relx=0.48, rely=0.12, relheight=0.03, relwidth=0.09)
        self.TEntry1.configure(width=166)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.TEntry2 = ttk.Entry(top)
        self.TEntry2.place(relx=0.48, rely=0.16, relheight=0.03, relwidth=0.09)
        self.TEntry2.configure(width=166)
        self.TEntry2.configure(takefocus="")
        self.TEntry2.configure(cursor="ibeam")

        self.TEntry3 = ttk.Entry(top)
        self.TEntry3.place(relx=0.48, rely=0.21, relheight=0.03, relwidth=0.09)
        self.TEntry3.configure(width=166)
        self.TEntry3.configure(takefocus="")
        self.TEntry3.configure(cursor="ibeam")

        self.TEntry4 = ttk.Entry(top)
        self.TEntry4.place(relx=0.48, rely=0.25, relheight=0.03, relwidth=0.09)
        self.TEntry4.configure(width=166)
        self.TEntry4.configure(takefocus="")
        self.TEntry4.configure(cursor="ibeam")

        self.TEntry5 = ttk.Entry(top)
        self.TEntry5.place(relx=0.48, rely=0.29, relheight=0.03, relwidth=0.09)
        self.TEntry5.configure(width=166)
        self.TEntry5.configure(takefocus="")
        self.TEntry5.configure(cursor="ibeam")

        self.TEntry6 = ttk.Entry(top)
        self.TEntry6.place(relx=0.49, rely=0.33, relheight=0.03, relwidth=0.09)
        self.TEntry6.configure(width=166)
        self.TEntry6.configure(takefocus="")
        self.TEntry6.configure(cursor="ibeam")

        self.TEntry7 = ttk.Entry(top)
        self.TEntry7.place(relx=0.49, rely=0.37, relheight=0.03, relwidth=0.09)
        self.TEntry7.configure(width=166)
        self.TEntry7.configure(takefocus="")
        self.TEntry7.configure(cursor="ibeam")

        self.TEntry8 = ttk.Entry(top)
        self.TEntry8.place(relx=0.49, rely=0.41, relheight=0.03, relwidth=0.09)
        self.TEntry8.configure(width=166)
        self.TEntry8.configure(takefocus="")
        self.TEntry8.configure(cursor="ibeam")

        self.TEntry9 = ttk.Entry(top)
        self.TEntry9.place(relx=0.49, rely=0.45, relheight=0.03, relwidth=0.09)
        self.TEntry9.configure(width=166)
        self.TEntry9.configure(takefocus="")
        self.TEntry9.configure(cursor="ibeam")

        self.TEntry10 = ttk.Entry(top)
        self.TEntry10.place(relx=0.49, rely=0.49, relheight=0.03, relwidth=0.09)
        self.TEntry10.configure(width=166)
        self.TEntry10.configure(takefocus="")
        self.TEntry10.configure(cursor="ibeam")

        self.TEntry11 = ttk.Entry(top)
        self.TEntry11.place(relx=0.49, rely=0.53, relheight=0.03, relwidth=0.09)
        self.TEntry11.configure(width=166)
        self.TEntry11.configure(takefocus="")
        self.TEntry11.configure(cursor="ibeam")

        self.TEntry12 = ttk.Entry(top)
        self.TEntry12.place(relx=0.49, rely=0.57, relheight=0.03, relwidth=0.09)
        self.TEntry12.configure(width=166)
        self.TEntry12.configure(takefocus="")
        self.TEntry12.configure(cursor="ibeam")

        self.TEntry13 = ttk.Entry(top)
        self.TEntry13.place(relx=0.49, rely=0.62, relheight=0.03, relwidth=0.09)
        self.TEntry13.configure(width=166)
        self.TEntry13.configure(takefocus="")
        self.TEntry13.configure(cursor="ibeam")

        self.TEntry14 = ttk.Entry(top)
        self.TEntry14.place(relx=0.49, rely=0.66, relheight=0.03, relwidth=0.09)
        self.TEntry14.configure(width=166)
        self.TEntry14.configure(takefocus="")
        self.TEntry14.configure(cursor="ibeam")

        self.TEntry15 = ttk.Entry(top)
        self.TEntry15.place(relx=0.49, rely=0.7, relheight=0.03, relwidth=0.09)
        self.TEntry15.configure(width=166)
        self.TEntry15.configure(takefocus="")
        self.TEntry15.configure(cursor="ibeam")

        self.TEntry16 = ttk.Entry(top)
        self.TEntry16.place(relx=0.49, rely=0.74, relheight=0.03, relwidth=0.09)
        self.TEntry16.configure(width=166)
        self.TEntry16.configure(takefocus="")
        self.TEntry16.configure(cursor="ibeam")

        self.TEntry17 = ttk.Entry(top)
        self.TEntry17.place(relx=0.5, rely=0.78, relheight=0.03, relwidth=0.09)
        self.TEntry17.configure(width=166)
        self.TEntry17.configure(takefocus="")
        self.TEntry17.configure(cursor="ibeam")

        self.TEntry18 = ttk.Entry(top)
        self.TEntry18.place(relx=0.49, rely=0.82, relheight=0.03, relwidth=0.09)
        self.TEntry18.configure(width=166)
        self.TEntry18.configure(takefocus="")
        self.TEntry18.configure(cursor="ibeam")

        self.TEntry19 = ttk.Entry(top)
        self.TEntry19.place(relx=0.5, rely=0.86, relheight=0.03, relwidth=0.09)
        self.TEntry19.configure(width=166)
        self.TEntry19.configure(takefocus="")
        self.TEntry19.configure(cursor="ibeam")

        self.TEntry20 = ttk.Entry(top)
        self.TEntry20.place(relx=0.49, rely=0.9, relheight=0.03, relwidth=0.09)
        self.TEntry20.configure(width=166)
        self.TEntry20.configure(takefocus="")
        self.TEntry20.configure(cursor="ibeam")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.73, rely=0.82, height=78, width=346)
        self.Button1.configure(activebackground="#d8d0cf")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d85e00")
        self.Button1.configure(command=market_menu1_support.calculatePrice)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="#f4ffc9")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#f9fff7")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''CheckOut''')
        self.Button1.configure(width=346)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="Arial 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

    @staticmethod
    def popup2(event, *args, **kwargs):
        Popupmenu2 = Menu(root, tearoff=0)
        Popupmenu2.configure(activebackground="#f9f9f9")
        Popupmenu2.configure(activeborderwidth="1")
        Popupmenu2.configure(activeforeground="black")
        Popupmenu2.configure(background="#d9d9d9")
        Popupmenu2.configure(borderwidth="1")
        Popupmenu2.configure(disabledforeground="#a3a3a3")
        Popupmenu2.configure(font="Arial 9")
        Popupmenu2.configure(foreground="black")
        Popupmenu2.post(event.x_root, event.y_root)

    @staticmethod
    def popup3(event, *args, **kwargs):
        Popupmenu3 = Menu(root, tearoff=0)
        Popupmenu3.configure(activebackground="#f9f9f9")
        Popupmenu3.configure(activeborderwidth="1")
        Popupmenu3.configure(activeforeground="black")
        Popupmenu3.configure(background="#d9d9d9")
        Popupmenu3.configure(borderwidth="1")
        Popupmenu3.configure(disabledforeground="#a3a3a3")
        Popupmenu3.configure(font="Arial 9")
        Popupmenu3.configure(foreground="black")
        Popupmenu3.post(event.x_root, event.y_root)

    @staticmethod
    def popup4(event, *args, **kwargs):
        Popupmenu4 = Menu(root, tearoff=0)
        Popupmenu4.configure(activebackground="#f9f9f9")
        Popupmenu4.configure(activeborderwidth="1")
        Popupmenu4.configure(activeforeground="black")
        Popupmenu4.configure(background="#d9d9d9")
        Popupmenu4.configure(borderwidth="1")
        Popupmenu4.configure(disabledforeground="#a3a3a3")
        Popupmenu4.configure(font="Arial 9")
        Popupmenu4.configure(foreground="black")
        Popupmenu4.post(event.x_root, event.y_root)

    @staticmethod
    def popup5(event, *args, **kwargs):
        Popupmenu5 = Menu(root, tearoff=0)
        Popupmenu5.configure(activebackground="#f9f9f9")
        Popupmenu5.configure(activeborderwidth="1")
        Popupmenu5.configure(activeforeground="black")
        Popupmenu5.configure(background="#d9d9d9")
        Popupmenu5.configure(borderwidth="1")
        Popupmenu5.configure(disabledforeground="#a3a3a3")
        Popupmenu5.configure(font="Arial 9")
        Popupmenu5.configure(foreground="black")
        Popupmenu5.post(event.x_root, event.y_root)






if __name__ == '__main__':
    vp_start_gui()


